title: Dhruv Kapadia
logo: 
email: dkapa at illinois.edu
blank_title: true
favicon: true
description: ""
show_downloads: false
remote_theme: BDHU/minimalist
color-scheme: auto
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-seo-tag

theme: jekyll-theme-tactile